### ISSUE TITLE
Failed to run distance supervision code

### ISSUE THREAD

**Issue by chengchingwen** [skgabriel/paracomet#1]
Hi, I try to run the distance supervision code, but I get a  `ModuleNotFoundError: No module named 'utils.utils'; 'utils' is not a package` when loading the comet model.

**Comment by skgabriel** [comment]
Hi, this might be an environment issue. The code was originally run using python 3.6.9 on a linux OS, but you may need to make adjustments depending on your environment.

**Comment by chengchingwen** [comment]
Interestingly, I'm also running with python 3.6.9 on Ubuntu. 

OTOH, the error occurs because the origin model pickle save the custom class `DD` in that pickle data. Due to the internal design of pickle format, it only save the import path, which is `utils.utils` in comet-commonsense. In comet-commonsense there is a folder named `utils` and inside it is a file named `utils.py`, which is the location of class `DD`. However, at paracomet we didn't import that `utils` folder but instead import only the `utils.py`. Therefore when loading the pickle, it try to get `utils.utils` but the `utils` here is different.

**Comment by skgabriel** [comment]
I see, you can try rerunning it with the pretrained comet-atomic model saved here: https://drive.google.com/drive/folders/17QQM9oVAS-vY-tIHUxjR2e2Sz3DBVYjj?usp=sharing.

**Comment by chengchingwen** [comment]
Thanks! The above model file works!

One more question, Are there any released `train-processed.jsonl` file or script for preprocess the rocstory data into `train-processed.jsonl`?

**Comment by skgabriel** [comment]
I added a link to the preprocessed data in the instructions

**Comment by chengchingwen** [comment]
Thanks for the fast response! I tried to run the code, but then I get dimension mismatch error from pytorch after running for one hours. Do you have any ideas on what the problem could be?

```
  1%|▌                                                                            | 685/98161 [59:10<140:21:28,  5.18s/it]Traceback (most recent call last):
  File "distant_supervision.py", line 451, in <module>
    main(args)
  File "distant_supervision.py", line 389, in main
    all_retrievals.append((idx, [[_format_comet_output(comet_model.predict(sent, dimensions_of_interest, "beam-10"),kg_type=args.kg_type)]]))
  File "../utils/atomic_demo.py", line 81, in predict
    self.text_encoder, categories)
  File "../utils/comet_functions.py", line 561, in get_atomic_sequence
    input_event, model, sampler, data_loader, text_encoder, cat)
  File "../utils/comet_functions.py", line 589, in get_atomic_sequence
    input_event, category, data_loader, text_encoder)
  File "../utils/comet_functions.py", line 630, in set_atomic_inputs
    XMB[:, :len(prefix)] = torch.LongTensor(prefix)
RuntimeError: The expanded size of the tensor (18) must match the existing size (20) at non-singleton dimension 1.  Target sizes: [1, 18].  Tensor sizes: [20]
```

**Comment by skgabriel** [comment]
Hi, the comet model has a fixed input size so in rare cases longer length inputs have to be truncated. I updated the code here (https://github.com/skgabriel/paracomet/blob/main/src/utils/comet_atomic.py) to use the version that automatically does this.

**Comment by chengchingwen** [comment]
Thanks! now it runs successfully.
