### ISSUE TITLE
HTTP request sent, awaiting response... 404 Not Found

### ISSUE THREAD

**Issue by knosing** [skgabriel/paracomet#5]
Hello there, 
Thanks for the repo. and code for paracomet. 
However, I am unable to download the ATOMIC data and keep getting this error. 
<img width="990" alt="image" src="https://user-images.githubusercontent.com/45248239/157166745-69162b74-5425-4087-9d3a-d821c43d47b0.png">
Any help would be greatly appreciated. 
Thanks.

**Comment by knosing** [comment]
Sorry I fixed it, the data is moved to a new location : https://storage.googleapis.com/ai2-mosaic/public/atomic/v1.0/atomic_data.tgz 
Resolved!

**Comment by Ontopic** [comment]
Maybe fix in README as well :)

**Comment by skgabriel** [comment]
Thanks for pointing this out, I'll update the README!
